// Windows design and engineering software, for the early access picker. Each
// entry is [name, vendor, category, aliases?]; aliases are extra search terms
// people actually type ("sw", "fusion 360", "c4d").

import { buildIndex, fold, search } from "./search";

export type Software = readonly [
  name: string,
  vendor: string,
  category: string,
  aliases?: string,
];

/** Shown as tiles before anything is typed. Names must match the catalogue. */
export const POPULAR = [
  "AutoCAD",
  "Revit",
  "SolidWorks",
  "Fusion",
  "Inventor",
  "Rhino",
  "SketchUp",
  "Civil 3D",
  "Archicad",
  "3ds Max",
  "Enscape",
  "Ansys Mechanical",
] as const;

export const SOFTWARE: readonly Software[] = [
  // General CAD and drafting
  ["AutoCAD", "Autodesk", "CAD", "acad"],
  ["AutoCAD LT", "Autodesk", "CAD"],
  ["AutoCAD Architecture", "Autodesk", "Architecture"],
  ["AutoCAD Mechanical", "Autodesk", "Mechanical"],
  ["AutoCAD Electrical", "Autodesk", "Electrical"],
  ["AutoCAD MEP", "Autodesk", "MEP"],
  ["AutoCAD Map 3D", "Autodesk", "GIS"],
  ["AutoCAD Plant 3D", "Autodesk", "Plant"],
  ["BricsCAD", "Bricsys", "CAD"],
  ["BricsCAD BIM", "Bricsys", "BIM"],
  ["DraftSight", "Dassault Systèmes", "CAD"],
  ["ZWCAD", "ZWSOFT", "CAD"],
  ["ZW3D", "ZWSOFT", "Mechanical"],
  ["progeCAD", "progeSOFT", "CAD"],
  ["GstarCAD", "Gstarsoft", "CAD"],
  ["IntelliCAD", "IntelliCAD Technology Consortium", "CAD"],
  ["TurboCAD", "IMSI Design", "CAD"],
  ["MicroStation", "Bentley", "CAD"],
  ["QCAD", "RibbonSoft", "CAD"],
  ["LibreCAD", "LibreCAD", "CAD"],
  ["DesignCAD", "IMSI Design", "CAD"],
  ["CorelCAD", "Corel", "CAD"],
  ["Caddie", "Advanced Computer Solutions", "CAD"],

  // Architecture and BIM
  ["Revit", "Autodesk", "BIM", "rvt"],
  ["Revit LT", "Autodesk", "BIM"],
  ["Archicad", "Graphisoft", "BIM"],
  ["Vectorworks Architect", "Vectorworks", "BIM"],
  ["Vectorworks Landmark", "Vectorworks", "Landscape"],
  ["Vectorworks Spotlight", "Vectorworks", "Entertainment"],
  ["Allplan", "Nemetschek", "BIM"],
  ["Tekla Structures", "Trimble", "BIM"],
  ["OpenBuildings Designer", "Bentley", "BIM", "aecosim"],
  ["Chief Architect", "Chief Architect", "Residential"],
  ["Home Designer", "Chief Architect", "Residential"],
  ["SoftPlan", "SoftPlan Systems", "Residential"],
  ["Envisioneer", "Cadsoft", "Residential"],
  ["Edificius", "ACCA Software", "BIM"],
  ["Cadwork", "cadwork", "Timber"],
  ["hsbcad", "hsbcad", "Timber"],
  ["Dietrich's", "Dietrich's", "Timber"],
  ["SketchUp", "Trimble", "3D modelling", "sketch up"],
  ["Rhino", "McNeel", "3D modelling", "rhinoceros rhino 3d"],
  ["Grasshopper", "McNeel", "Computational design", "gh"],
  ["Dynamo", "Autodesk", "Computational design"],
  ["Rhino.Inside.Revit", "McNeel", "Computational design"],
  ["Forma", "Autodesk", "Site planning", "spacemaker"],
  ["FormIt", "Autodesk", "Architecture"],
  ["Navisworks", "Autodesk", "Coordination"],
  ["Solibri", "Nemetschek", "Model checking"],
  ["Revizto", "Revizto", "Coordination"],
  ["Synchro 4D", "Bentley", "Construction"],
  ["iTwin", "Bentley", "Digital twin"],
  ["Lands Design", "Asuni", "Landscape"],
  ["Land F/X", "Land F/X", "Landscape"],
  ["DIALux evo", "DIAL", "Lighting"],
  ["Relux", "Relux Informatik", "Lighting"],
  ["AGi32", "Lighting Analysts", "Lighting"],
  ["IES VE", "IES", "Energy"],
  ["DesignBuilder", "DesignBuilder", "Energy", "energyplus"],
  ["Sefaira", "Trimble", "Energy"],
  ["Ladybug Tools", "Ladybug Tools", "Environmental analysis", "honeybee"],
  ["Bluebeam Revu", "Bluebeam", "Markup", "pdf"],
  ["PlanSwift", "ConstructConnect", "Estimating", "takeoff"],
  ["Primavera P6", "Oracle", "Scheduling"],
  ["Microsoft Project", "Microsoft", "Scheduling", "ms project"],

  // Interiors, kitchens, joinery
  ["2020 Design Live", "Cyncly", "Kitchen and bath"],
  ["Cabinet Vision", "Hexagon", "Cabinetry"],
  ["Microvellum", "Microvellum", "Cabinetry"],
  ["KitchenDraw", "KitchenDraw", "Kitchen and bath"],
  ["Polyboard", "Wood Designer", "Cabinetry"],
  ["Pytha", "Pytha", "Interiors"],
  ["imos iX", "Homag", "Cabinetry"],

  // Civil, infrastructure, survey, GIS
  ["Civil 3D", "Autodesk", "Civil", "c3d"],
  ["InfraWorks", "Autodesk", "Civil"],
  ["OpenRoads Designer", "Bentley", "Civil"],
  ["OpenRail Designer", "Bentley", "Rail"],
  ["OpenBridge Modeler", "Bentley", "Bridges"],
  ["OpenFlows WaterGEMS", "Bentley", "Water"],
  ["OpenFlows SewerGEMS", "Bentley", "Water"],
  ["OpenFlows FLOOD", "Bentley", "Water"],
  ["12d Model", "12d Solutions", "Civil"],
  ["Carlson Civil", "Carlson Software", "Civil"],
  ["Carlson Survey", "Carlson Software", "Survey"],
  ["Trimble Business Center", "Trimble", "Survey", "tbc"],
  ["Magnet Office", "Topcon", "Survey"],
  ["Leica Infinity", "Leica Geosystems", "Survey"],
  ["Leica Cyclone", "Leica Geosystems", "Point clouds"],
  ["ReCap Pro", "Autodesk", "Point clouds"],
  ["FARO Scene", "FARO", "Point clouds"],
  ["CloudCompare", "CloudCompare", "Point clouds"],
  ["Agisoft Metashape", "Agisoft", "Photogrammetry"],
  ["Pix4Dmapper", "Pix4D", "Photogrammetry"],
  ["RealityCapture", "Epic Games", "Photogrammetry", "reality scan"],
  ["ContextCapture", "Bentley", "Photogrammetry", "itwin capture"],
  ["ArcGIS Pro", "Esri", "GIS"],
  ["ArcMap", "Esri", "GIS"],
  ["QGIS", "QGIS", "GIS"],
  ["Global Mapper", "Blue Marble", "GIS"],
  ["HEC-RAS", "US Army Corps of Engineers", "Hydraulics"],
  ["HEC-HMS", "US Army Corps of Engineers", "Hydrology"],
  ["InfoWorks ICM", "Autodesk", "Hydraulics"],
  ["SWMM", "US EPA", "Hydraulics"],
  ["EPANET", "US EPA", "Water"],
  ["Synchro Studio", "Trimble", "Traffic"],
  ["Vissim", "PTV", "Traffic"],
  ["AutoTURN", "Transoft", "Traffic"],
  ["Vehicle Tracking", "Autodesk", "Traffic"],

  // Structural and geotechnical
  ["ETABS", "CSI", "Structural"],
  ["SAP2000", "CSI", "Structural"],
  ["SAFE", "CSI", "Structural"],
  ["CSiBridge", "CSI", "Bridges"],
  ["Robot Structural Analysis", "Autodesk", "Structural"],
  ["STAAD.Pro", "Bentley", "Structural", "staad"],
  ["RAM Structural System", "Bentley", "Structural"],
  ["RISA-3D", "RISA", "Structural"],
  ["RISAFloor", "RISA", "Structural"],
  ["RFEM", "Dlubal", "Structural"],
  ["RSTAB", "Dlubal", "Structural"],
  ["SCIA Engineer", "Nemetschek", "Structural"],
  ["Tekla Structural Designer", "Trimble", "Structural"],
  ["Tekla Tedds", "Trimble", "Structural"],
  ["IDEA StatiCa", "IDEA StatiCa", "Connections"],
  ["Advance Steel", "Autodesk", "Steel detailing"],
  ["Advance Concrete", "Autodesk", "Concrete detailing"],
  ["midas Civil", "MIDAS", "Bridges"],
  ["midas Gen", "MIDAS", "Structural"],
  ["SPACE GASS", "SPACE GASS", "Structural"],
  ["Strand7", "Strand7", "Structural"],
  ["Prokon", "Prokon", "Structural"],
  ["Enercalc", "Enercalc", "Structural"],
  ["SkyCiv", "SkyCiv", "Structural"],
  ["Sofistik", "Sofistik", "Structural"],
  ["Karamba3D", "Karamba3D", "Structural"],
  ["PLAXIS", "Bentley", "Geotechnical"],
  ["GeoStudio", "Seequent", "Geotechnical"],
  ["FLAC3D", "Itasca", "Geotechnical"],
  ["RS2", "Rocscience", "Geotechnical"],
  ["Slide2", "Rocscience", "Geotechnical"],
  ["gINT", "Bentley", "Geotechnical"],
  ["Leapfrog", "Seequent", "Geology"],

  // MEP and electrical
  ["MagiCAD", "MagiCAD Group", "MEP"],
  ["Fabrication CADmep", "Autodesk", "MEP"],
  ["Trimble SysQue", "Trimble", "MEP"],
  ["Trane TRACE 3D Plus", "Trane", "HVAC"],
  ["Carrier HAP", "Carrier", "HVAC"],
  ["Elite CHVAC", "Elite Software", "HVAC"],
  ["Hevacomp", "Bentley", "MEP"],
  ["EPLAN Electric P8", "EPLAN", "Electrical"],
  ["SEE Electrical", "IGE+XAO", "Electrical"],
  ["SolidWorks Electrical", "Dassault Systèmes", "Electrical"],
  ["ETAP", "ETAP", "Power systems"],
  ["SKM PowerTools", "SKM", "Power systems"],
  ["EasyPower", "EasyPower", "Power systems"],
  ["PSS/E", "Siemens", "Power systems"],
  ["DIgSILENT PowerFactory", "DIgSILENT", "Power systems"],
  ["PVsyst", "PVsyst", "Solar"],
  ["HelioScope", "Aurora Solar", "Solar"],

  // Mechanical and product design
  ["SolidWorks", "Dassault Systèmes", "Mechanical", "sw solid works"],
  ["Inventor", "Autodesk", "Mechanical"],
  ["Fusion", "Autodesk", "Mechanical", "fusion 360 f360"],
  ["CATIA", "Dassault Systèmes", "Mechanical"],
  ["3DEXPERIENCE", "Dassault Systèmes", "Mechanical", "3dx"],
  ["Siemens NX", "Siemens", "Mechanical", "unigraphics"],
  ["Solid Edge", "Siemens", "Mechanical"],
  ["Creo", "PTC", "Mechanical", "pro/engineer proe"],
  ["Onshape", "PTC", "Mechanical"],
  ["IronCAD", "IronCAD", "Mechanical"],
  ["SpaceClaim", "Ansys", "Mechanical"],
  ["Ansys Discovery", "Ansys", "Mechanical"],
  ["DesignSpark Mechanical", "RS Components", "Mechanical"],
  ["FreeCAD", "FreeCAD", "Mechanical"],
  ["Shapr3D", "Shapr3D", "Mechanical"],
  ["Alibre Design", "Alibre", "Mechanical"],
  ["KeyCreator", "Kubotek", "Mechanical"],
  ["Cimatron", "Cimatron", "Tooling"],
  ["think3", "think3", "Mechanical"],
  ["Alias", "Autodesk", "Industrial design", "autostudio"],
  ["VRED", "Autodesk", "Visualisation"],
  ["Gravity Sketch", "Gravity Sketch", "Industrial design"],
  ["SolidWorks Composer", "Dassault Systèmes", "Technical docs"],
  ["SolidWorks PDM", "Dassault Systèmes", "Data management"],
  ["Vault", "Autodesk", "Data management"],
  ["Windchill", "PTC", "Data management"],
  ["Teamcenter", "Siemens", "Data management"],
  ["Factory Design Utilities", "Autodesk", "Factory layout"],
  ["Plant Simulation", "Siemens", "Factory simulation", "tecnomatix"],
  ["AVEVA E3D", "AVEVA", "Plant"],
  ["AVEVA PDMS", "AVEVA", "Plant"],
  ["Smart 3D", "Hexagon", "Plant", "smartplant"],
  ["CADWorx", "Hexagon", "Plant"],
  ["CAESAR II", "Hexagon", "Pipe stress"],
  ["ShipConstructor", "SSI", "Marine"],
  ["Maxsurf", "Bentley", "Marine"],
  ["Orca3D", "DRS", "Marine"],

  // CAM and manufacturing
  ["Mastercam", "CNC Software", "CAM"],
  ["PowerMill", "Autodesk", "CAM"],
  ["FeatureCAM", "Autodesk", "CAM"],
  ["Inventor CAM", "Autodesk", "CAM", "hsmworks"],
  ["SolidCAM", "SolidCAM", "CAM"],
  ["CAMWorks", "HCL", "CAM"],
  ["hyperMILL", "Open Mind", "CAM"],
  ["Esprit", "Hexagon", "CAM"],
  ["GibbsCAM", "Cimatron", "CAM"],
  ["NX CAM", "Siemens", "CAM"],
  ["edgecam", "Hexagon", "CAM"],
  ["WorkNC", "Hexagon", "CAM"],
  ["BobCAD-CAM", "BobCAD", "CAM"],
  ["Vectric Aspire", "Vectric", "CAM"],
  ["Vectric VCarve", "Vectric", "CAM"],
  ["SigmaNEST", "SigmaTEK", "Nesting"],
  ["Lantek", "Lantek", "Sheet metal"],
  ["Radan", "Hexagon", "Sheet metal"],
  ["Materialise Magics", "Materialise", "3D printing"],
  ["Netfabb", "Autodesk", "3D printing"],
  ["UltiMaker Cura", "UltiMaker", "3D printing"],
  ["PrusaSlicer", "Prusa Research", "3D printing"],
  ["PolyWorks", "InnovMetric", "Metrology"],
  ["PC-DMIS", "Hexagon", "Metrology"],
  ["Geomagic Design X", "Hexagon", "Reverse engineering"],
  ["Geomagic Control X", "Hexagon", "Metrology"],

  // Simulation and analysis
  ["Ansys Mechanical", "Ansys", "Simulation", "workbench fea"],
  ["Ansys Fluent", "Ansys", "CFD"],
  ["Ansys CFX", "Ansys", "CFD"],
  ["Ansys HFSS", "Ansys", "Electromagnetics"],
  ["Ansys Maxwell", "Ansys", "Electromagnetics"],
  ["Ansys LS-DYNA", "Ansys", "Simulation", "lsdyna"],
  ["Ansys Granta", "Ansys", "Materials"],
  ["Abaqus", "Dassault Systèmes", "Simulation", "simulia"],
  ["COMSOL Multiphysics", "COMSOL", "Simulation"],
  ["MSC Nastran", "Hexagon", "Simulation"],
  ["Patran", "Hexagon", "Simulation"],
  ["Adams", "Hexagon", "Multibody dynamics"],
  ["Femap", "Siemens", "Simulation"],
  ["Simcenter 3D", "Siemens", "Simulation"],
  ["Simcenter STAR-CCM+", "Siemens", "CFD", "starccm"],
  ["Simcenter Amesim", "Siemens", "System simulation"],
  ["HyperMesh", "Altair", "Simulation"],
  ["Altair OptiStruct", "Altair", "Simulation"],
  ["Altair Inspire", "Altair", "Simulation"],
  ["Altair SimSolid", "Altair", "Simulation"],
  ["SolidWorks Simulation", "Dassault Systèmes", "Simulation"],
  ["SolidWorks Flow Simulation", "Dassault Systèmes", "CFD"],
  ["Autodesk CFD", "Autodesk", "CFD"],
  ["Moldflow", "Autodesk", "Plastics"],
  ["Moldex3D", "CoreTech", "Plastics"],
  ["CST Studio Suite", "Dassault Systèmes", "Electromagnetics"],
  ["OpenFOAM", "OpenFOAM", "CFD"],
  ["SimScale", "SimScale", "Simulation"],
  ["MATLAB", "MathWorks", "Engineering computing"],
  ["Simulink", "MathWorks", "System simulation"],
  ["LabVIEW", "NI", "Test and measurement"],
  ["Mathcad", "PTC", "Engineering computing"],

  // Electronics
  ["Altium Designer", "Altium", "PCB"],
  ["KiCad", "KiCad", "PCB"],
  ["OrCAD", "Cadence", "PCB"],
  ["Allegro", "Cadence", "PCB"],
  ["PADS", "Siemens", "PCB"],
  ["Xpedition", "Siemens", "PCB"],
  ["Fusion Electronics", "Autodesk", "PCB", "eagle"],
  ["Proteus", "Labcenter", "PCB"],
  ["LTspice", "Analog Devices", "Circuit simulation"],
  ["Multisim", "NI", "Circuit simulation"],
  ["Quartus Prime", "Intel", "FPGA"],
  ["Vivado", "AMD", "FPGA", "xilinx"],
  ["TIA Portal", "Siemens", "Automation", "step 7 plc"],
  ["Studio 5000", "Rockwell Automation", "Automation", "rslogix plc"],
  ["CODESYS", "CODESYS", "Automation", "plc"],

  // Visualisation, rendering, 3D content
  ["3ds Max", "Autodesk", "3D modelling", "3dsmax max"],
  ["Maya", "Autodesk", "3D animation"],
  ["Blender", "Blender Foundation", "3D modelling"],
  ["Cinema 4D", "Maxon", "3D animation", "c4d"],
  ["Houdini", "SideFX", "3D effects"],
  ["ZBrush", "Maxon", "Sculpting"],
  ["Substance 3D Painter", "Adobe", "Texturing"],
  ["Substance 3D Designer", "Adobe", "Texturing"],
  ["Marvelous Designer", "CLO Virtual Fashion", "Cloth"],
  ["Enscape", "Chaos", "Rendering"],
  ["V-Ray", "Chaos", "Rendering", "vray"],
  ["Corona Renderer", "Chaos", "Rendering"],
  ["Chaos Vantage", "Chaos", "Rendering"],
  ["Lumion", "Act-3D", "Rendering"],
  ["Twinmotion", "Epic Games", "Rendering"],
  ["D5 Render", "D5", "Rendering"],
  ["KeyShot", "KeyShot", "Rendering"],
  ["Unreal Engine", "Epic Games", "Real-time", "ue5"],
  ["Unity", "Unity", "Real-time"],
  ["LumenRT", "Bentley", "Rendering"],
  ["Arnold", "Autodesk", "Rendering"],
  ["Redshift", "Maxon", "Rendering"],
  ["Octane Render", "OTOY", "Rendering"],

  // Jewellery, fashion, footwear
  ["MatrixGold", "Stuller", "Jewellery", "gemvision"],
  ["RhinoGold", "Stuller", "Jewellery"],
  ["CLO 3D", "CLO Virtual Fashion", "Fashion"],
  ["Browzwear VStitcher", "Browzwear", "Fashion"],
  ["Optitex", "EFI", "Fashion"],
];

const popularSet = new Set<string>(POPULAR);

// Aliases are space-separated short forms; the vendor and category only count
// when nothing in the name does ("autodesk" lists Autodesk's apps).
const index = buildIndex(
  SOFTWARE.map((s) => ({
    software: s,
    name: s[0],
    aliases: s[3]?.split(" "),
    context: `${s[1]} ${s[2]}`,
    rank: popularSet.has(s[0]) ? 120 : 0,
  })),
);

/** Best matches first, forgiving short forms and slips; see search.ts. */
export function searchSoftware(query: string, limit = 8): Software[] {
  return search(index, query, limit).map((x) => x.software);
}

/** The catalogue's spelling of a name, if it has one. */
export function findSoftware(name: string): Software | undefined {
  const q = fold(name);
  return index.entries.find((e) => e.name === q)?.item.software;
}
